" vim: fdm=marker fmr={{{,}}}
" Personal vimrc from Josh Surber http://github.com/joshsurber
"
" Plugins managed by vim-plug, :PlugInstall/:PlugUpdate
"
" Leader is spacebar
"
let s:coc = 0

" Future organization:
" Launching vim
" Buffers, windows, and tabs
" Creating files
" Locating/opening files
" Viewing files
" Navigating files
" Editing files
" Inserting text
" Writing files

" Basic setup {{{
set cindent
" set showcmd     " Show last :cmd in statusline
set hidden      " Allow unsaved buffers in background
set visualbell  " Flash instead of beep
" set title       " Automatically set term title to filename
" set ttyfast     " Update screen faster
set lazyredraw  " Don't redraw screen while executing macros
set showbreak=↪ " Indicator at the start of wrapped lines
set splitbelow | set splitright  " New vsplit will be to right of current one
set cursorline  " Highlight current line
set spell       " Spellcheck by default
set updatetime=500  " update twice a second
set dictionary=/usr/share/dict/words
set scrolloff=5 | set sidescrolloff=5

" Time out on key codes but not mappings.
" Basically this makes terminal Vim work sanely.
set notimeout

set noswapfile " How often does vim crash anyway?
set undodir=~/.vim/undo//

set path+=** " Allows for fuzzy-like :find-ing

" }}}
" Tabs, spaces, wrapping {{{
" set softtabstop=4   " Insert spaces instead of tabs when typing
set formatoptions=qrn1 " Autoformat code comments
set shiftround      " Round indent to multiple of shiftwidth

" Wrap long lines, but not in the middle of a word, and maintain indent level
set wrap | set linebreak | set breakindent

" highlight trailing whitespace
match ErrorMsg '\s\+$'
" " remove trailing whitespaces automatically
autocmd BufWritePre * :%s/\s\+$//e

" }}}
" Sane line numbers{{{
set number relativenumber " Current line actual line number, other relative to cursor

augroup numbertoggle
    " Use relative numbers only in the active buffer
    autocmd!
    autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
    autocmd BufLeave,FocusLost,InsertEnter   * set norelativenumber
augroup END

" }}}
" Menus in the console{{{
" This will duplicate the same menus used in gVim, by pressing space,semicolon
" source $VIMRUNTIME/menu.vim
set wildmenu
set wildmode=list:longest,full " Expand as much as possible, then show the list
" set wildmode=longest:full,full                 "How the completion is done
" set cpoptions-=< " disable recognizing key codes |cpo-<|
" set wcm=<C-Z>
" map <leader>; :emenu <C-Z>
set wildignorecase                             "Case insensitive completion

set wildignore+=*.tags,tags                    " ignore tags files
set wildignore+=..git                          " Version control
set wildignore+=*.jpg,*.bmp,*.gif,*.png,*.jpeg " binary images
set wildignore+=*.sw?,.bak                     " Vim swap files

" }}}
" Leader {{{
let mapleader = "\<Space>""

" Simple write and quit
noremap <leader>w :w<cr>
noremap <leader>qq :q<cr>
noremap QQ :q<cr>

" recover borked terminal
noremap <leader>l :redraw!<cr>

" Toggle folds easily
nnoremap <leader><leader> za
vnoremap <leader><leader> za

" Edit and source .vimrc simply
nnoremap <leader>ve :edit $MYVIMRC<cr>
nnoremap <leader>vs :source $MYVIMRC<cr>

" }}}
" Windows and tabs{{{
" Control+HJKL navigates windows
noremap <C-h>  <C-w>h
noremap <C-j>  <C-w>j
noremap <C-k>  <C-w>k
noremap <C-l>  <C-w>l

" Resize splits with arrows. They don't serve any other purpose, right?
" Commented to see if it is why I have trouble with COC lists
nnoremap <C-Up>    :resize +2<CR>
nnoremap <C-Down>  :resize -2<CR>
nnoremap <C-Left>  :vertical resize +2<CR>
nnoremap <C-Right> :vertical resize -2<CR>

" Resize splits when the window is resized
au VimResized * exe "normal! \<c-w>="

" Open help window on right
augroup vimrc_help
    autocmd!
    autocmd BufEnter *.txt if &buftype == 'help' | wincmd L | endif
augroup END
"}}}
" Text navigaion{{{
" Searching and movement
nnoremap / /\v
vnoremap / /\v

" Case insensitive searching, unless search includes uppercase letters, including during insert completion
set ignorecase | set smartcase | set infercase
" Do not use smart case in command line mode,
if exists('##CmdLineEnter')
 	augroup dynamic_smartcase
		autocmd!
		autocmd CmdLineEnter : set nosmartcase
		autocmd CmdLineLeave : set smartcase
	augroup END
endif

set showmatch   " Highlight matching brackets as you type
set hlsearch    " highlight search results, leader\ set elsewhere to remove
noremap <leader>\ :noh<cr>      " remove search highlighting
" set gdefault    " Sub command defaults to whole lines


" Lines wrap. Deal with it...
noremap j gj
noremap k gk

" find matching brace etc with tab
map <tab> %

vnoremap <C-j> :m '>+1<CR>gv=gv
vnoremap <C-k> :m '<-2<CR>gv=gv
noremap <C-z> :set wrap!<CR>:set wrap?<CR>

" Open a Quickfix window for the last search.
nnoremap <silent> <leader>/ :execute 'vimgrep /'.@/.'/g %'<CR>:copen<CR>

"}}}
" Selection{{{
set virtualedit+=block " Rect selections can encompass blank chars

" " Fix linewise visual selection of various text objects
nnoremap VV V
nnoremap Vit vitVkoj
nnoremap Vat vatV
nnoremap Vab vabV
nnoremap VaB vaBV

"}}}
" Inserting, editing, and saving {{{
" Move to end of pasted text; easily select same
vnoremap <silent> y y`]
vnoremap <silent> p p`]
nnoremap <silent> p p`]
noremap gV `[v`]

" System clipboard commands
set clipboard=unnamed       " Use system clipboard to yank and put
" vmap <Leader>y "+y        " None of the rest matters because of the above
" vmap <Leader>d "+d        " Will delete if no issues arrive from using system cb
" nmap <Leader>p "+p
" nmap <Leader>P "+P
" vmap <Leader>p "+p
" vmap <Leader>P "+P

"}}}
" Filetype specific{{{
au BufRead $MYVIMRC set fdm=marker " Use folds in this file

" Simplify navigaion of vim help
autocmd FileType help nnoremap <buffer> <CR> <C-]>
autocmd FileType help nnoremap <buffer> <BS> <C-T>
" autocmd FileType help nnoremap <buffer> o /'\l\{2,\}'<CR>
" autocmd FileType help nnoremap <buffer> O ?'\l\{2,\}'<CR>
" autocmd FileType help nnoremap <buffer> s /\|\zs\S\+\ze\|<CR>
" autocmd FileType help nnoremap <buffer> S ?\|\zs\S\+\ze\|<CR>

" Make sure all markdown files have the correct filetype set and setup wrapping
" au BufRead,BufNewFile *.{md,markdown,mdown,mkd,mkdn,txt} setf markdown | call s:setupWrapping()

" Treat JSON files like JavaScript
au BufNewFile,BufRead *.json setf javascript

autocmd FileType css  setlocal fdm=syntax
autocmd FileType scss setlocal fdm=syntax

" magic markers: enable using `H/S/J/C to jump back to
" last HTML, stylesheet, JS or Ruby code buffer
au BufLeave *.{erb,html}      exe "normal! mH"
au BufLeave *.{css,scss,sass} exe "normal! mS"
au BufLeave *.{js,coffee}     exe "normal! mJ"
au BufLeave *.{rb}            exe "normal! mC"
"}}}
" Misc{{{
set keywordprg=:help " K opens vimhelp not manpage

inoremap jk <esc> " Faster Esc
vnoremap jk <esc> " Faster Esc

cmap w!! w !sudo tee % >/dev/null " No write permission? Fuck you, do it anyway!

" expand %% to current directory in command-line mode
cnoremap %% <C-R>=expand('%:h').'/'<cr>
"}}}
" Plugin install {{{
" Setup for Vim Plug .{{{
" Download and install vim-plug (cross platform)
if empty(glob(
            \ '$HOME/' . (has('win32') ? 'vimfiles' : '.vim') . '/autoload/plug.vim'))
    execute '!curl -fLo ' .
                \ (has('win32') ? '\%USERPROFILE\%/vimfiles' : '$HOME/.vim') .
                \ '/autoload/plug.vim --create-dirs ' .
                \ 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Run PlugInstall if there are missing plugins
autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
            \| PlugInstall --sync | source $MYVIMRC
            \| endif

"}}}

call plug#begin()

" Plug 'Yggdroot/indentLine'              " Make indents easier to follow
" Plug 'airblade/vim-rooter'              " Change working directory to project base
" Plug 'flazz/vim-colorschemes'
" Plug 'junegunn/vim-peekaboo'            " Show registers when summoned
" Plug 'junegunn/vim-plug'                " Installs docs with vimplug
" Plug 'lifepillar/vim-mucomplete'
" Plug 'terryma/vim-expand-region'
" Plug 'tpope/vim-flagship'
" Plug 'vim-scripts/Gundo'                " visualize the undo tree
" Plug 'vim-scripts/ScrollColors'         " Browse colorschemes easily
Plug 'AndrewRadev/tagalong.vim'         " Modify HTML tags in pairs
Plug 'airblade/vim-gitgutter'           " Keep track of changes in git
Plug 'alvan/vim-closetag'
Plug 'ap/vim-css-color'                 " Colors in CSS
Plug 'hail2u/vim-css3-syntax'
Plug 'jiangmiao/auto-pairs'             " Automatically close braces
Plug 'junegunn/fzf' | Plug 'junegunn/fzf.vim'
Plug 'mattn/emmet-vim' | Plug 'mattn/webapi-vim'
Plug 'prettier/vim-prettier'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-eunuch'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-obsession'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-sleuth'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-vinegar'
Plug 'vim-airline/vim-airline' | Plug 'vim-airline/vim-airline-themes'
Plug 'vim-scripts/CSSMinister'          " Convert color formats

if s:coc|Plug 'neoclide/coc.nvim', {'branch': 'release'}|endif

call plug#end()

" }}}
" Plugin configuration{{{
" " Netrw : emulate NERDtree {{{
" let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_browse_split = 4
" let g:netrw_altv = 1
let g:netrw_winsize = 25
nmap <silent> <C-e> :Lexplore<CR>
" " augroup ProjectDrawer
" "   autocmd!
" "   autocmd VimEnter * :Vexplore
" " augroup END
" " }}}
" Airline{{{
" let g:airline_theme='solarized'
" let g:airline_solarized_bg='dark'
let g:airline_powerline_fonts = 1
if !exists('g:airline_symbols')
    let g:airline_symbols = {}
endif
let g:airline_symbols.space = "\ua0"
let g:airline#parts#ffenc#skip_expected_string='utf-8[unix]'
"}}}
" Expand region{{{
vmap v <Plug>(expand_region_expand)
vmap <C-v> <Plug>(expand_region_shrink)
"}}}
" Color scheme {{{
set background=dark
colorscheme gruvbox "solarized8_dark
if !has('gui_running')
    set t_Co=256
endif
"}}}
" fzf {{{
" nnoremap <leader>p :find *
nnoremap <leader>p :<C-u>FZF<CR>
"}}}
" Tagalong {{{
let g:tagalong_verbose = 1
"}}}
" Emmet {{{
"enable all function in all mode.
let g:user_emmet_mode='a'
" enable just for html/css
let g:user_emmet_install_global = 1
autocmd filetype html,css,scss,markdown EmmetInstall
let g:emmet_html5 = 1
let g:user_emmet_leader_key = ','

let g:user_emmet_settings = webapi#json#decode(join(readfile(expand('~/.vim/snippets.json')), "\n"))
"}}}
" Prettier {{{
let g:prettier#autoformat = 1
let g:prettier#autoformat_require_pragma = 0
let g:prettier#config#use_tabs = 'false'
"}}}
" Indent line {{{
let g:indentLine_fileTypeExclude = ['help']
let g:indentLine_char = '┊'
let g:indentLine_char_list = ['|', '¦', '┆', '┊']
let g:indentLine_fileType = ['html','css','javascript']
"}}}
if s:coc " CoC{{{
let g:coc_global_extensions = [
\ 'coc-marketplace',
\ 'coc-sh',
\ 'coc-css',
\ 'coc-emmet',
\ 'coc-eslint',
\ 'coc-html',
\ 'coc-json',
\ 'coc-pairs',
\ 'coc-prettier',
\ 'coc-stylelint',
\ 'coc-html-css-support',
\ 'coc-tsserver',
\ ]
" \ 'coc-sql',
" \ 'coc-spell-checker',
" \ 'coc-htmlhint',
" EVERYTHING BELOW IS COPIED DIRECTLY FROM THE COC README FILE

" Don't pass messages to |ins-completion-menu|.
set shortmess+=c

" Always show the signcolumn, otherwise it would shift the text each time
" diagnostics appear/become resolved.
" if has("nvim-0.5.0") || has("patch-8.1.1564")
"     " Recently vim can merge signcolumn and number column into one
"     set signcolumn=number
" else
"     set signcolumn=yes
" endif

" Use tab for trigger completion with characters ahead and navigate.
" NOTE: Use command ':verbose imap <tab>' to make sure tab is not mapped by
" other plugin before putting this into your config.
inoremap <silent><expr> <TAB>
            \ pumvisible() ? "\<C-n>" :
            \ <SID>check_back_space() ? "\<TAB>" :
            \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

function! s:check_back_space() abort
    let col = col('.') - 1
    return !col || getline('.')[col - 1]  =~# '\s'
endfunction

" " Use <c-space> to trigger completion.
" if has('nvim')
"     inoremap <silent><expr> <c-space> coc#refresh()
" else
"     inoremap <silent><expr> <c-@> coc#refresh()
" endif

" Make <CR> auto-select the first completion item and notify coc.nvim to
" format on enter, <cr> could be remapped by other vim plugin
inoremap <silent><expr> <cr> pumvisible() ? coc#_select_confirm()
            \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"

" " Use `[g` and `]g` to navigate diagnostics
" " Use `:CocDiagnostics` to get all diagnostics of current buffer in location list.
" nmap <silent> [g <Plug>(coc-diagnostic-prev)
" nmap <silent> ]g <Plug>(coc-diagnostic-next)

" " GoTo code navigation.
" nmap <silent> gd <Plug>(coc-definition)
" nmap <silent> gy <Plug>(coc-type-definition)
" nmap <silent> gi <Plug>(coc-implementation)
" nmap <silent> gr <Plug>(coc-references)

" Use K to show documentation in preview window.
nnoremap <silent> K :call <SID>show_documentation()<CR>

function! s:show_documentation()
    if (index(['vim','help'], &filetype) >= 0)
        execute 'h '.expand('<cword>')
    elseif (coc#rpc#ready())
        call CocActionAsync('doHover')
    else
        execute '!' . &keywordprg . " " . expand('<cword>')
    endif
endfunction

" Highlight the symbol and its references when holding the cursor.
autocmd CursorHold * silent call CocActionAsync('highlight')

" Symbol renaming.
nmap <leader>rn <Plug>(coc-rename)

" " Formatting selected code.
" xmap <leader>f  <Plug>(coc-format-selected)
" nmap <leader>f  <Plug>(coc-format-selected)

augroup mygroup
    autocmd!
    " Setup formatexpr specified filetype(s).
    autocmd FileType typescript,json setl formatexpr=CocAction('formatSelected')
    " Update signature help on jump placeholder.
    autocmd User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')
augroup end

" " Applying codeAction to the selected region.
" " Example: `<leader>aap` for current paragraph
" xmap <leader>a  <Plug>(coc-codeaction-selected)
" nmap <leader>a  <Plug>(coc-codeaction-selected)

" " Remap keys for applying codeAction to the current buffer.
" nmap <leader>ac  <Plug>(coc-codeaction)
" " Apply AutoFix to problem on the current line.
" nmap <leader>qf  <Plug>(coc-fix-current)

" " Run the Code Lens action on the current line.
" nmap <leader>cl  <Plug>(coc-codelens-action)

" " Map function and class text objects
" " NOTE: Requires 'textDocument.documentSymbol' support from the language server.
" xmap if <Plug>(coc-funcobj-i)
" omap if <Plug>(coc-funcobj-i)
" xmap af <Plug>(coc-funcobj-a)
" omap af <Plug>(coc-funcobj-a)
" xmap ic <Plug>(coc-classobj-i)
" omap ic <Plug>(coc-classobj-i)
" xmap ac <Plug>(coc-classobj-a)
" omap ac <Plug>(coc-classobj-a)

" Remap <C-f> and <C-b> for scroll float windows/popups.
if has('nvim-0.4.0') || has('patch-8.2.0750')
    nnoremap <silent><nowait><expr> <C-f> coc#float#has_scroll() ? coc#float#scroll(1) : "\<C-f>"
    nnoremap <silent><nowait><expr> <C-b> coc#float#has_scroll() ? coc#float#scroll(0) : "\<C-b>"
    inoremap <silent><nowait><expr> <C-f> coc#float#has_scroll() ? "\<c-r>=coc#float#scroll(1)\<cr>" : "\<Right>"
    inoremap <silent><nowait><expr> <C-b> coc#float#has_scroll() ? "\<c-r>=coc#float#scroll(0)\<cr>" : "\<Left>"
    vnoremap <silent><nowait><expr> <C-f> coc#float#has_scroll() ? coc#float#scroll(1) : "\<C-f>"
    vnoremap <silent><nowait><expr> <C-b> coc#float#has_scroll() ? coc#float#scroll(0) : "\<C-b>"
endif

" " Use CTRL-S for selections ranges.
" " Requires 'textDocument/selectionRange' support of language server.
" nmap <silent> <C-s> <Plug>(coc-range-select)
" xmap <silent> <C-s> <Plug>(coc-range-select)

" Add `:Format` command to format current buffer.
command! -nargs=0 Format :call CocActionAsync('format')

" Add `:Fold` command to fold current buffer.
command! -nargs=? Fold :call     CocAction('fold', <f-args>)

" Add `:OR` command for organize imports of the current buffer.
command! -nargs=0 OR   :call     CocActionAsync('runCommand', 'editor.action.organizeImport')

" Add (Neo)Vim's native statusline support.
" NOTE: Please see `:h coc-status` for integrations with external plugins that
" provide custom statusline: lightline.vim, vim-airline.
set statusline^=%{coc#status()}%{get(b:,'coc_current_function','')}

" Mappings for CoCList
" Show all diagnostics.
nnoremap <silent><nowait> <space>a  :<C-u>CocList diagnostics<cr>
" Manage extensions.
nnoremap <silent><nowait> <space>e  :<C-u>CocList extensions<cr>
" Show commands.
nnoremap <silent><nowait> <space>c  :<C-u>CocList commands<cr>
" Find symbol of current document.
nnoremap <silent><nowait> <space>o  :<C-u>CocList outline<cr>
" Search workspace symbols.
nnoremap <silent><nowait> <space>s  :<C-u>CocList -I symbols<cr>
" Do default action for next item.
nnoremap <silent><nowait> <space>j  :<C-u>CocNext<CR>
" Do default action for previous item.
nnoremap <silent><nowait> <space>k  :<C-u>CocPrev<CR>
" Resume latest coc list.
" nnoremap <silent><nowait> <space>p  :<C-u>CocListResume<CR>
endif " }}}
" }}}
"
" bookmarked directories {{{
nnoremap <leader>fs  :edit ~/Sites/**/*
nnoremap <leader>fd  :edit ~/Documents/**/*
nnoremap <leader>fv  :edit ~/.vim/**/*
nnoremap <leader>fh  :edit ~/**/*
" }}} " bookmarked directories

" Next Completion On / {{{ 1
" better navigation of command history
" allow next completion after / alternative
" is <C-E> if <C-D> makes to long of a list
" cnoremap <expr> / wildmenumode() ? "\<C-E>" : "/"
" 1 }}} "Next Completion On /

" Commandline Abbreviations {{{
" if we have 3 * in a row make them into **/*
" this is only applied on the end of a line
cnoremap <expr> * getcmdline() =~ '.*\*\*$' ? '/*' : '*'
" full path shortcut
cnoreabbr <expr> %% fnameescape(expand('%:p'))
" }}}

" nnoremap ]b :silent! bnext<CR>
" nnoremap [b :silent! bprevious<CR>
