#!/bin/bash

# MODERN ALTERNATIVES
alias vi=$EDITOR
# alias find='fdfind' # mint
alias find='fd' # manjango
alias more='less' # less is more
alias cat='batcat'
alias open='xdg-open'

# TYPING SAVERS
alias bv='back&&vi'
alias f='fd'
alias i='sudo pacman -S' # manjango
# alias i='sudo apt install' # mint
alias o='open'
alias v='vi'

# MOVE AROUND
alias up='cd ..'
alias back='cd -'
alias cdvi='cd ~/.config/nvim/'

# LS ALIASES
alias cls="clear;ls"
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'

# WEB DEV ALIASES
alias serve='browser-sync start --server --files . > /dev/null '

# QUICKFIX COMMON MISTAKES
alias fuck='sudo $(history -p \!\!)' # As in "fuck, I forgot to sudo that command!"
alias moar='$(history -p \!\!) | less' # Run the last command through more (actually less)
