#!/bin/bash

# MODERN ALTERNATIVES
alias vi=$EDITOR
alias find=$FIND
alias more='less' # less is more
alias cat=$CAT
alias open='xdg-open'

# TYPING SAVERS
alias bv='back&&vi'
alias f=$FIND
alias i=$INSTALL
alias o='open'
alias v='vi'

# SHORT GIT ALIASES (using same mnemonics from nvim)
alias gg='git status'
alias gc='git commit'
alias gd='git diff'
alias gp='git push'
alias gs='git add' # git stage

# MOVE AROUND
alias up='cd ..'
alias back='cd -'
alias cdvi='cd ~/.config/nvim/'

# LS ALIASES
alias cls="clear;ls"
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'

# WEB DEV ALIASES
alias serve='browser-sync start --server --files . > /dev/null '

# QUICKFIX COMMON MISTAKES
alias fuck='sudo $(history -p \!\!)' # As in "fuck, I forgot to sudo that command!"
alias moar='$(history -p \!\!) | less' # Run the last command through more (actually less)
