#!/bin/bash

# This is the ugliness required to keep up with different application names and paths between the different distros I use

# The path for fzf's completion scripts
[[ -e /usr/share/doc/fzf/examples ]] && export FZFDIR='/usr/share/doc/fzf/examples'
[[ -e /usr/share/fzf ]] && export FZFDIR='/usr/share/fzf/'

# fd is called fdfind in some distros
if [ -x "$(command -v fd)" ]; then
    export FIND='fd'
elif [ -x "$(command -v fdfind)" ]; then
    export FIND='fdfind'
else
    export FIND='find'
fi

# bat is called batcat in some distros
if [ -x "$(command -v bat)" ]; then
    export CAT='bat'
elif [ -x "$(command -v batcat)" ]; then
    export CAT='batcat'
else
    export CAT='cat'
fi

# pacman vs apt to insall packages
if [ -x "$(command -v apt)" ]; then
    export INSTALL='sudo apt install'
elif [ -x "$(command -v pacman)" ]; then
    export INSTALL='sudo pacman -S'
fi
