#!/bin/bash
# COMMON APPS
export EDITOR=nvim
export VISUAL=$EDITOR
export PAGER=less
export BROWSER=qutebrowser
export TERMINAL=kitty
export DMENU=rofi
export FIND=fd

# PATHS
export PATH=~/.local/bin:~/.cargo/bin:$PATH:/opt/nvim-linux64/bin
export CDPATH=.:~

# FZF
export FZF_DEFAULT_COMMAND="$FIND --type f --strip-cwd-prefix --exclude .git"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# CLIPMENU
export CM_LAUNCHER=$DMENU
export CM_SELECTIONS=clipboard

[[ -x "$(command -v setxkbmap)" ]] && setxkbmap -option caps:escape 2> /dev/null
source $HOME/.bashrc
