#!/bin/bash
source ~/.bash/env
source ~/.bash/aliases
source ~/.bash/functions

# STARSHIP PROMPT
# install with `curl -sS https://starship.rs/install.sh | sh`
# or `cargo install starship`
eval "$(starship init bash)"

# Autocomplete pandoc options
eval "$(pandoc --bash-completion)"

# FZF
# source /usr/share/doc/fzf/examples/key-bindings.bash # mint
# source /usr/share/doc/fzf/examples/completion.bash # mint
source /usr/share/fzf/key-bindings.bash # manjango
source /usr/share/fzf/completion.bash # manjango

source /usr/share/doc/pkgfile/command-not-found.bash # manjango

neofetch
