#!/bin/bash
# This file just sources all the other files I use to configure bash

source ~/.bash/env
source ~/.bash/aliases
source ~/.bash/functions

# Help find command to install if not available
[[ -r /usr/share/doc/pkgfile ]] && source /usr/share/doc/pkgfile/command-not-found.bash

# FZF
[[ -e /usr/share/doc/fzf/examples/ ]] && source /usr/share/doc/fzf/examples/key-bindings.bash
[[ -e /usr/share/doc/fzf/ ]] && source /usr/share/doc/fzf/exampleskey-bindings.bash 2> /dev/null && source /usr/share/doc/fzf/examplescompletion.bash
[[ -e /usr/share/fzf/ ]] && source /usr/share/fzf/key-bindings.bash && source /usr/share/fzf/completion.bash

[ -x "$(command -v starship)" ] && eval "$(starship init bash)"
[ -x "$(command -v starship)" ] && eval "$(starship completions bash)"
[ -x "$(command -v pandoc)" ] && eval "$(pandoc --bash-completion)"
[ -x "$(command -v zoxide)" ] && eval "$(zoxide init bash)"

# neofetch
