# Install webscreensaver https://github.com/lmartinking/webscreensaver
# Available in AUR. Then add this line to .xscreensaver
# webscreensaver -sites-list $HOME/.config/system47.toml   \n\

[system47]
# Clone system47 to repos dir (move if desired)
# https://github.com/webOSpinn/System47
url = 'file:///home/josh/repos/System47/app/v8.0/audio/index.html'
[starfield47]
url = 'https://www.mewho.com/starfield47/'
[ritos47]
url = 'https://www.mewho.com/ritos/'
