#! /bin/sh

pgrep -x sxhkd -m 1> /dev/null || sxhkd -m -1 &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         2
bspc config window_gap          4

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

dunst &
polybar-msg cmd quit &
polybar -r &
nitrogen --restore &
clipmenud &
picom &
