add_newline = false

[[battery.display]]
threshold = 100
style = "green"

[[battery.display]]
threshold = 75
style = "yellow"


[[battery.display]]
threshold = 50
style = "bold yellow"


[[battery.display]]
threshold = 25
style = "bold red"



[line_break]
disabled = true
